name: 🐛 Bug Report
description: Found a bug? Help us squash it.
labels: ["bug"]

body:

- type: markdown
  attributes:
    value: |
      Consider [supporting the project](https://github.com/sponsors/alexdlaird) ❤ to have your request prioritized.

- type: checkboxes
  id: ack
  attributes:
    label: Acknowledgements
    options:
    - label: I have written a descriptive issue title
      required: true
    - label: I have searched [`amazon-orders`'s documentation](https://amazon-orders.readthedocs.io/en/latest/) for an answer
      required: true
    - label: I have searched [Issues](issues?q=is%3Aissue) to see if the bug has already been reported
      required: true
    - label: I have searched [Stack Overflow](https://stackoverflow.com/questions/) to ensure the issue I'm experiencing has not already been discussed
      required: true
    - label: I have [enabled `debug` mode](https://amazon-orders.readthedocs.io/troubleshooting.html#enable-debug-mode) and am attaching relevant console logs and HTML files

- type: input
  id: os-version
  attributes:
    label: Operating System
    placeholder: macOS 10.14.5
  validations:
    required: true

- type: input
  id: python-version
  attributes:
    label: Python Version
    placeholder: 3.9.2
  validations:
    required: true

- type: input
  id: amazon-url
  attributes:
    label: What URL are you directed to when logging in to your Amazon account?
    placeholder: https://www.amazon.com/ap/signin
  validations:
    required: true

- type: input
  id: library-version
  attributes:
    label: amazon-orders Version
    placeholder: 1.0.3
  validations:
    required: true

- type: textarea
  id: describe-the-bug
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is, including exceptions thrown.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: A snippet of the code used to reproduce the behavior.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: A brief description of what you expected to happen.
